Added Github Releases tags and circle ci workflow
SoSocio/EslintConfig pull request #3
Opened 2022-10-17 10:58 UTC by Dhaxor

2022-10-17 17:58 UTC, jotmaster requested changes

2022-10-17 17:58 UTC, jotmaster commented on Dockerfile
> +# RUN echo "doppler run -- npm run build" >> ${ENTRYPOINT_DIR}/entry_point.sh
Uncomment or remove?

2022-10-19 07:05 UTC, OluwmayowaF approved these changes

2022-10-24 17:08 UTC, jotmaster approved these changes

2022-10-25 07:44 UTC, merged