Update node version from 14 to 16
SoSocio/EslintConfig pull request #5
Opened 2023-03-13 13:59 UTC by Dhaxor

## PULL REQUEST TEMPLATE
Please replace all lines starting with [ ] with [x] to check them

## checklist
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] CI related changes
- [x] Requires dependency update?
- [ ] Other... Please describe:

## What changes did you make? (Give an overview)
- Update node version from 14 to 16
## Is there anything you'd like reviewers to focus on?
No
## Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)
No

2023-03-14 08:06 UTC, OluwmayowaF approved these changes, later dismissed

2023-03-14 14:04 UTC, bjornbos requested changes

2023-03-14 14:04 UTC, bjornbos commented on Backend/README.md
> +npm install @sosocio/eslint-config-backend@1.0.14
The upcoming release is going to be v1.1.0

2023-03-14 14:04 UTC, bjornbos commented on Backend/package.json
> +  "version": "1.0.14",
The upcoming release is going to be v1.1.0

2023-03-14 14:04 UTC, bjornbos commented on Backend/package.json
> +    "@sosocio/eslint-config": "^1.0.34"
The upcoming release is going to be v1.1.0

2023-03-14 14:04 UTC, bjornbos commented on Frontend/README.md
> +npm install @sosocio/eslint-config-frontend@1.0.20
The upcoming release is going to be v1.1.0

2023-03-14 14:04 UTC, bjornbos commented on Frontend/package.json
> +  "version": "1.0.20",
The upcoming release is going to be v1.1.0

2023-03-14 14:04 UTC, bjornbos commented on Frontend/package.json
> +    "@sosocio/eslint-config": "^1.0.34"
The upcoming release is going to be v1.1.0

2023-03-14 14:04 UTC, bjornbos commented on README.md
> +npm install @sosocio/eslint-config-frontend@1.0.20
The upcoming release is going to be v1.1.0

2023-03-14 14:04 UTC, bjornbos commented on README.md
> +npm install @sosocio/eslint-config-backend@1.0.14
The upcoming release is going to be v1.1.0

2023-03-14 14:04 UTC, bjornbos commented on package.json
> +	"version": "1.0.34",
The upcoming release is going to be v1.1.0

2023-03-16 08:52 UTC, bjornbos approved these changes

2023-03-16 14:05 UTC, jotmaster approved these changes

2023-03-17 07:55 UTC, OluwmayowaF approved these changes

2023-03-17 10:10 UTC, merged